/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[3] */
/* Routed pin properties */
#define BOARD_ENET_CRS_DV_PERIPHERAL                                         ARM   /*!< Peripheral name */
#define BOARD_ENET_CRS_DV_SIGNAL                                   arm_trace_swo   /*!< Signal name */

/* GPIO_AD_B0_15 (number 93), ENET_TXD1/U11[25]/J19[2] */
/* Routed pin properties */
#define BOARD_ENET_TXD1_PERIPHERAL                                       LPUART3   /*!< Peripheral name */
#define BOARD_ENET_TXD1_SIGNAL                                                RX   /*!< Signal name */

/* GPIO_AD_B0_14 (number 94), ENET_TXD0/U11[24]/J17[7] */
/* Routed pin properties */
#define BOARD_ENET_TXD0_PERIPHERAL                                       LPUART3   /*!< Peripheral name */
#define BOARD_ENET_TXD0_SIGNAL                                                TX   /*!< Signal name */

/* WAKEUP (number 52), USER_BUTTON */
/* Routed pin properties */
#define BOARD_USER_BUTTON_PERIPHERAL                                       GPIO5   /*!< Peripheral name */
#define BOARD_USER_BUTTON_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_USER_BUTTON_CHANNEL                                             0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_USER_BUTTON_GPIO                                             GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_USER_BUTTON_GPIO_PIN                                            0U   /*!< GPIO pin number */
#define BOARD_USER_BUTTON_GPIO_PIN_MASK                               (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_USER_BUTTON_PORT                                             GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_USER_BUTTON_PIN                                                 0U   /*!< PORT pin number */
#define BOARD_USER_BUTTON_PIN_MASK                                    (1U << 0U)   /*!< PORT pin mask */

/* GPIO_AD_B0_04 (number 107), JTAG_TDO/J16[13]/ENET_RST/U11[32] */
/* Routed pin properties */
#define BOARD_ENET_RST_PERIPHERAL                                           JTAG   /*!< Peripheral name */
#define BOARD_ENET_RST_SIGNAL                                                TDO   /*!< Signal name */

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define BOARD_ENET_RXD0_PERIPHERAL                                        LPSPI1   /*!< Peripheral name */
#define BOARD_ENET_RXD0_SIGNAL                                               SCK   /*!< Signal name */

/* GPIO_AD_B0_13 (number 95), ENET_TXEN/U11[23]/J19[5] */
/* Routed pin properties */
#define BOARD_ENET_TXEN_PERIPHERAL                                        LPSPI1   /*!< Peripheral name */
#define BOARD_ENET_TXEN_SIGNAL                                               SDI   /*!< Signal name */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define BOARD_ENET_RXER_PERIPHERAL                                        LPSPI1   /*!< Peripheral name */
#define BOARD_ENET_RXER_SIGNAL                                               SDO   /*!< Signal name */

/* GPIO_AD_B0_09 (number 99), ENET_RXD1/U11[15]/J17[3] */
/* Routed pin properties */
#define BOARD_ENET_RXD1_PERIPHERAL                                         GPIO1   /*!< Peripheral name */
#define BOARD_ENET_RXD1_SIGNAL                                           gpio_io   /*!< Signal name */
#define BOARD_ENET_RXD1_CHANNEL                                               9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENET_RXD1_GPIO                                               GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_ENET_RXD1_GPIO_PIN                                              9U   /*!< GPIO pin number */
#define BOARD_ENET_RXD1_GPIO_PIN_MASK                                 (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_ENET_RXD1_PORT                                               GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_ENET_RXD1_PIN                                                   9U   /*!< PORT pin number */
#define BOARD_ENET_RXD1_PIN_MASK                                      (1U << 9U)   /*!< PORT pin mask */

/* GPIO_AD_B1_13 (number 76), CAN_STBY/J18[4] */
/* Routed pin properties */
#define BOARD_CAN_STBY_PERIPHERAL                                          GPIO1   /*!< Peripheral name */
#define BOARD_CAN_STBY_SIGNAL                                            gpio_io   /*!< Signal name */
#define BOARD_CAN_STBY_CHANNEL                                               29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_CAN_STBY_GPIO                                                GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_CAN_STBY_GPIO_PIN                                              29U   /*!< GPIO pin number */
#define BOARD_CAN_STBY_GPIO_PIN_MASK                                 (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_CAN_STBY_PORT                                                GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_CAN_STBY_PIN                                                   29U   /*!< PORT pin number */
#define BOARD_CAN_STBY_PIN_MASK                                      (1U << 29U)   /*!< PORT pin mask */

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_UART1_RXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_RXD_SIGNAL                                                RX   /*!< Signal name */

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_UART1_TXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_TXD_SIGNAL                                                TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
