/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_lpuart_freertos.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the backround buffer size */
#define LPUART1_BACKGROUND_BUFFER_SIZE 1
/* LPUART1 interrupt vector ID (number). */
#define LPUART1_IRQN LPUART1_IRQn
/* LPUART1 interrupt vector priority. */
#define LPUART1_IRQ_PRIORITY 5
/* Definition of peripheral ID */
#define LPUART3_PERIPHERAL LPUART3
/* Definition of the backround buffer size */
#define LPUART3_BACKGROUND_BUFFER_SIZE 1
/* LPUART3 interrupt vector ID (number). */
#define LPUART3_IRQN LPUART3_IRQn
/* LPUART3 interrupt vector priority. */
#define LPUART3_IRQ_PRIORITY 5
/* Definition of peripheral ID */
#define LPUART4_PERIPHERAL LPUART4
/* Definition of the backround buffer size */
#define LPUART4_BACKGROUND_BUFFER_SIZE 1
/* LPUART4 interrupt vector ID (number). */
#define LPUART4_IRQN LPUART4_IRQn
/* LPUART4 interrupt vector priority. */
#define LPUART4_IRQ_PRIORITY 5

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern lpuart_rtos_handle_t LPUART1_rtos_handle;
extern lpuart_handle_t LPUART1_lpuart_handle;
extern lpuart_rtos_config_t LPUART1_rtos_config;
extern lpuart_rtos_handle_t LPUART3_rtos_handle;
extern lpuart_handle_t LPUART3_lpuart_handle;
extern lpuart_rtos_config_t LPUART3_rtos_config;
extern lpuart_rtos_handle_t LPUART4_rtos_handle;
extern lpuart_handle_t LPUART4_lpuart_handle;
extern lpuart_rtos_config_t LPUART4_rtos_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
