function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "FSW_Lib0"};
	this.sidHashMap["FSW_Lib0"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Main_Sim:593"};
	this.sidHashMap["Main_Sim:593"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Main_Sim:593:237"};
	this.sidHashMap["Main_Sim:593:237"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S1>/sensor_meas"] = {sid: "Main_Sim:593:6"};
	this.sidHashMap["Main_Sim:593:6"] = {rtwname: "<S1>/sensor_meas"};
	this.rtwnameHashMap["<S1>/Bus Assignment"] = {sid: "Main_Sim:593:217"};
	this.sidHashMap["Main_Sim:593:217"] = {rtwname: "<S1>/Bus Assignment"};
	this.rtwnameHashMap["<S1>/Bus Selector"] = {sid: "Main_Sim:593:357"};
	this.sidHashMap["Main_Sim:593:357"] = {rtwname: "<S1>/Bus Selector"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "Main_Sim:593:392"};
	this.sidHashMap["Main_Sim:593:392"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Constant1"] = {sid: "Main_Sim:593:393"};
	this.sidHashMap["Main_Sim:593:393"] = {rtwname: "<S1>/Constant1"};
	this.rtwnameHashMap["<S1>/Rate Transition6"] = {sid: "Main_Sim:593:376"};
	this.sidHashMap["Main_Sim:593:376"] = {rtwname: "<S1>/Rate Transition6"};
	this.rtwnameHashMap["<S1>/Rate Transition7"] = {sid: "Main_Sim:593:377"};
	this.sidHashMap["Main_Sim:593:377"] = {rtwname: "<S1>/Rate Transition7"};
	this.rtwnameHashMap["<S1>/Terminator"] = {sid: "Main_Sim:593:389"};
	this.sidHashMap["Main_Sim:593:389"] = {rtwname: "<S1>/Terminator"};
	this.rtwnameHashMap["<S1>/Terminator1"] = {sid: "Main_Sim:593:390"};
	this.sidHashMap["Main_Sim:593:390"] = {rtwname: "<S1>/Terminator1"};
	this.rtwnameHashMap["<S1>/Terminator2"] = {sid: "Main_Sim:593:391"};
	this.sidHashMap["Main_Sim:593:391"] = {rtwname: "<S1>/Terminator2"};
	this.rtwnameHashMap["<S1>/fsw_out_bus"] = {sid: "Main_Sim:593:237"};
	this.sidHashMap["Main_Sim:593:237"] = {rtwname: "<S1>/fsw_out_bus"};
	this.rtwnameHashMap["<S1>/fsw_out"] = {sid: "Main_Sim:593:7"};
	this.sidHashMap["Main_Sim:593:7"] = {rtwname: "<S1>/fsw_out"};
	this.rtwnameHashMap["<S2>/Bus Creator"] = {sid: "Main_Sim:593:237:2"};
	this.sidHashMap["Main_Sim:593:237:2"] = {rtwname: "<S2>/Bus Creator"};
	this.rtwnameHashMap["<S2>/Constant1"] = {sid: "Main_Sim:593:237:3"};
	this.sidHashMap["Main_Sim:593:237:3"] = {rtwname: "<S2>/Constant1"};
	this.rtwnameHashMap["<S2>/Constant7"] = {sid: "Main_Sim:593:237:6"};
	this.sidHashMap["Main_Sim:593:237:6"] = {rtwname: "<S2>/Constant7"};
	this.rtwnameHashMap["<S2>/bus stub"] = {sid: "Main_Sim:593:237:7"};
	this.sidHashMap["Main_Sim:593:237:7"] = {rtwname: "<S2>/bus stub"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
