/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 6.0.1
board: IMXRT1050-EVKB
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H2, peripheral: LPUART8, signal: TX, pin_signal: GPIO_SD_B0_04}
  - {pin_num: J2, peripheral: LPUART8, signal: RX, pin_signal: GPIO_SD_B0_05}
  - {pin_num: B9, peripheral: LPUART3, signal: TX, pin_signal: GPIO_B0_08}
  - {pin_num: C9, peripheral: LPUART3, signal: RX, pin_signal: GPIO_B0_09}
  - {pin_num: D2, peripheral: LPUART6, signal: TX, pin_signal: GPIO_EMC_25}
  - {pin_num: B3, peripheral: LPUART6, signal: RX, pin_signal: GPIO_EMC_26}
  - {pin_num: E1, peripheral: LPSPI1, signal: SDI, pin_signal: GPIO_EMC_29}
  - {pin_num: D1, peripheral: LPSPI1, signal: SDO, pin_signal: GPIO_EMC_28}
  - {pin_num: A2, peripheral: LPSPI1, signal: SCK, pin_signal: GPIO_EMC_27}
  - {pin_num: C7, peripheral: LPSPI1, signal: PCS3, pin_signal: GPIO_EMC_41}
  - {pin_num: A7, peripheral: LPSPI1, signal: PCS2, pin_signal: GPIO_EMC_40}
  - {pin_num: C6, peripheral: LPSPI1, signal: PCS0, pin_signal: GPIO_EMC_30}
  - {pin_num: C5, peripheral: LPSPI1, signal: PCS1, pin_signal: GPIO_EMC_31}
  - {pin_num: C1, peripheral: LPI2C3, signal: SDA, pin_signal: GPIO_EMC_21}
  - {pin_num: F1, peripheral: LPI2C3, signal: SCL, pin_signal: GPIO_EMC_22}
  - {pin_num: P2, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_SD_B1_04}
  - {pin_num: N3, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_SD_B1_05}
  - {pin_num: P4, peripheral: LPI2C2, signal: SDA, pin_signal: GPIO_SD_B1_10}
  - {pin_num: P5, peripheral: LPI2C2, signal: SCL, pin_signal: GPIO_SD_B1_11}
  - {pin_num: D9, peripheral: GPIO2, signal: 'gpio_io, 10', pin_signal: GPIO_B0_10}
  - {pin_num: A9, peripheral: GPIO2, signal: 'gpio_io, 07', pin_signal: GPIO_B0_07}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_07_GPIO2_IO07,           /* GPIO_B0_07 is configured as GPIO2_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_B0_08_LPUART3_TX,           /* GPIO_B0_08 is configured as LPUART3_TX */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_B0_09_LPUART3_RX,           /* GPIO_B0_09 is configured as LPUART3_RX */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
  		IOMUXC_GPIO_AD_B1_06_LPUART3_TX,
        0U);
  IOMUXC_SetPinMux(
  		IOMUXC_GPIO_AD_B1_07_LPUART3_RX,
        0U);
// modified two UART3 pins to use the accessible ones

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_10_GPIO2_IO10,           /* GPIO_B0_10 is configured as GPIO2_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_21_LPI2C3_SDA,          /* GPIO_EMC_21 is configured as LPI2C3_SDA */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_22_LPI2C3_SCL,          /* GPIO_EMC_22 is configured as LPI2C3_SCL */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_25_LPUART6_TX,          /* GPIO_EMC_25 is configured as LPUART6_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_26_LPUART6_RX,          /* GPIO_EMC_26 is configured as LPUART6_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_27_LPSPI1_SCK,          /* GPIO_EMC_27 is configured as LPSPI1_SCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_28_LPSPI1_SDO,          /* GPIO_EMC_28 is configured as LPSPI1_SDO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_29_LPSPI1_SDI,          /* GPIO_EMC_29 is configured as LPSPI1_SDI */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_30_LPSPI1_PCS0,         /* GPIO_EMC_30 is configured as LPSPI1_PCS0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_31_LPSPI1_PCS1,         /* GPIO_EMC_31 is configured as LPSPI1_PCS1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_40_LPSPI1_PCS2,         /* GPIO_EMC_40 is configured as LPSPI1_PCS2 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_41_LPSPI1_PCS3,         /* GPIO_EMC_41 is configured as LPSPI1_PCS3 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_04_LPUART8_TX,        /* GPIO_SD_B0_04 is configured as LPUART8_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_05_LPUART8_RX,        /* GPIO_SD_B0_05 is configured as LPUART8_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_04_LPI2C1_SCL,        /* GPIO_SD_B1_04 is configured as LPI2C1_SCL */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_05_LPI2C1_SDA,        /* GPIO_SD_B1_05 is configured as LPI2C1_SDA */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_10_LPI2C2_SDA,        /* GPIO_SD_B1_10 is configured as LPI2C2_SDA */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_11_LPI2C2_SCL,        /* GPIO_SD_B1_11 is configured as LPI2C2_SCL */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
// I2C pin initializations make the program crash
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
