/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B0_04 (coord H2), SD1_D2 */
#define BOARD_INITPINS_SD1_D2_PERIPHERAL                                 LPUART8   /*!< Device name: LPUART8 */
#define BOARD_INITPINS_SD1_D2_SIGNAL                                          TX   /*!< LPUART8 signal: TX */

/* GPIO_SD_B0_05 (coord J2), SD1_D3 */
#define BOARD_INITPINS_SD1_D3_PERIPHERAL                                 LPUART8   /*!< Device name: LPUART8 */
#define BOARD_INITPINS_SD1_D3_SIGNAL                                          RX   /*!< LPUART8 signal: RX */

/* GPIO_B0_08 (coord B9), LCDIF_D4/BT_CFG[4] */
#define BOARD_INITPINS_LCDIF_D4_PERIPHERAL                               LPUART3   /*!< Device name: LPUART3 */
#define BOARD_INITPINS_LCDIF_D4_SIGNAL                                        TX   /*!< LPUART3 signal: TX */

/* GPIO_B0_09 (coord C9), LCDIF_D5/BT_CFG[5] */
#define BOARD_INITPINS_LCDIF_D5_PERIPHERAL                               LPUART3   /*!< Device name: LPUART3 */
#define BOARD_INITPINS_LCDIF_D5_SIGNAL                                        RX   /*!< LPUART3 signal: RX */

/* GPIO_EMC_25 (coord D2), SEMC_RAS */
#define BOARD_INITPINS_SEMC_RAS_PERIPHERAL                               LPUART6   /*!< Device name: LPUART6 */
#define BOARD_INITPINS_SEMC_RAS_SIGNAL                                        TX   /*!< LPUART6 signal: TX */

/* GPIO_EMC_26 (coord B3), SEMC_CLK */
#define BOARD_INITPINS_SEMC_CLK_PERIPHERAL                               LPUART6   /*!< Device name: LPUART6 */
#define BOARD_INITPINS_SEMC_CLK_SIGNAL                                        RX   /*!< LPUART6 signal: RX */

/* GPIO_EMC_29 (coord E1), SEMC_CS0 */
#define BOARD_INITPINS_SEMC_CS0_PERIPHERAL                                LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SEMC_CS0_SIGNAL                                       SDI   /*!< LPSPI1 signal: SDI */

/* GPIO_EMC_28 (coord D1), SEMC_WE */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                        SDO   /*!< LPSPI1 signal: SDO */

/* GPIO_EMC_27 (coord A2), SEMC_CKE */
#define BOARD_INITPINS_SEMC_CKE_PERIPHERAL                                LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SEMC_CKE_SIGNAL                                       SCK   /*!< LPSPI1 signal: SCK */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL                               LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL                                     PCS3   /*!< LPSPI1 signal: PCS3 */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                                LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                                      PCS2   /*!< LPSPI1 signal: PCS2 */

/* GPIO_EMC_30 (coord C6), SEMC_D8 */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                       PCS0   /*!< LPSPI1 signal: PCS0 */

/* GPIO_EMC_31 (coord C5), SEMC_D9 */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                       PCS1   /*!< LPSPI1 signal: PCS1 */

/* GPIO_EMC_21 (coord C1), SEMC_BA0 */
#define BOARD_INITPINS_SEMC_BA0_PERIPHERAL                                LPI2C3   /*!< Device name: LPI2C3 */
#define BOARD_INITPINS_SEMC_BA0_SIGNAL                                       SDA   /*!< LPI2C3 signal: SDA */

/* GPIO_EMC_22 (coord F1), SEMC_BA1 */
#define BOARD_INITPINS_SEMC_BA1_PERIPHERAL                                LPI2C3   /*!< Device name: LPI2C3 */
#define BOARD_INITPINS_SEMC_BA1_SIGNAL                                       SCL   /*!< LPI2C3 signal: SCL */

/* GPIO_SD_B1_04 (coord P2), FlexSPI_CLK_B */
#define BOARD_INITPINS_FlexSPI_CLK_B_PERIPHERAL                           LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_FlexSPI_CLK_B_SIGNAL                                  SCL   /*!< LPI2C1 signal: SCL */

/* GPIO_SD_B1_05 (coord N3), FlexSPI_DQS */
#define BOARD_INITPINS_FlexSPI_DQS_PERIPHERAL                             LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_FlexSPI_DQS_SIGNAL                                    SDA   /*!< LPI2C1 signal: SDA */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
#define BOARD_INITPINS_FlexSPI_D2_A_PERIPHERAL                            LPI2C2   /*!< Device name: LPI2C2 */
#define BOARD_INITPINS_FlexSPI_D2_A_SIGNAL                                   SDA   /*!< LPI2C2 signal: SDA */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
#define BOARD_INITPINS_FlexSPI_D3_A_PERIPHERAL                            LPI2C2   /*!< Device name: LPI2C2 */
#define BOARD_INITPINS_FlexSPI_D3_A_SIGNAL                                   SCL   /*!< LPI2C2 signal: SCL */

/* GPIO_B0_10 (coord D9), LCDIF_D6/BT_CFG[6] */
#define BOARD_INITPINS_LCDIF_D6_GPIO                                       GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D6_PORT                                       GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D6_PIN                                          10U   /*!< GPIO2 pin index: 10 */

/* GPIO_B0_07 (coord A9), LCDIF_D3/BT_CFG[3] */
#define BOARD_INITPINS_LCDIF_D3_GPIO                                       GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D3_PORT                                       GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D3_PIN                                           7U   /*!< GPIO2 pin index: 7 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
